{% set name = "jupyter-jaeger" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name | replace("-", "_") }}/{{ name | replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 46628417163b28e67298af0f782d00e2f5e8d106a94785cca4cd454abc70e73d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - flit
  run:
    - python
    - jaeger
    - jupyter-server-proxy
    - notebook

test:
  imports:
    - jupyter_jaeger

about:
  home: https://github.com/Quansight/jupyter-jaeger
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter integration for Jaeger tracing

extra:
  recipe-maintainers:
    - scopatz
